#!/bin/bash

# 安装 pytest
#python3 -m pip install pytest

#python3 -m unittest discover test 'test_*.py'
# pytest --collect-only
pytest
# pytest yop_python_sdk/tests --html=report.html --self-contained-html